language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.0
  - 7.1

install:
  - composer require --no-update roave/security-advisories:dev-master
  - composer install -n --no-progress

before_script:
  - vendor/bin/php-cs-fixer --diff --dry-run -v fix

script:
  - SYMFONY_DEPRECATIONS_HELPER=strict vendor/bin/phpunit -v

after_success:
  - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
  - php coveralls.phar -v --exclude-no-stmt

notifications:
  email: false
