language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.0
  - 7.1

install:
  - composer require --no-update satooshi/php-coveralls:~0.6
  - composer require --no-update roave/security-advisories:dev-master
  - composer install -n --no-progress

before_script:
  - vendor/bin/php-cs-fixer --diff --dry-run -v fix

script:
  - SYMFONY_DEPRECATIONS_HELPER=strict vendor/bin/phpunit -v

after_script:
  - vendor/bin/coveralls -v

notifications:
  email: false
